### ISSUE TITLE
Update all cmd-*-vpp repos that use edwarnicke/vpphelper

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/vpphelper#4]
Update all cmd-*-vpp repos that use `edwarnicke/vpphelper`. For example (cmd-nsc-vpp):
- Replace `github.com/edwarnicke/vpphelper v0.2.0` with `github.com/networkservicemesh/vpphelper main`
- Update imports in *.go files (edwarnicke --> networkservicemesh)
- go mod tidy

To test it:
- docker build -t {cmd-nsc-vpp} .
- use this image in your cluster

**Comment by bellycat77** [comment]
Also, need to do before commit:
```
go fmt
goimports -w -local github.com/networkservicemesh .
go generate ./...
```

**Comment by denis-tingaikin** [comment]
Seems like done. 

Other issues we'll consider in separate tickets.
